### ISSUE TITLE
Unable to attach VPN to environment

### ISSUE THREAD

**Issue by 5f6b3fb8** [skytap/docker-machine-driver-skytap#15]
toolbox version: 1.11.1/windows
docker-machine.exe version 0.7.0, build a650a40
docker-machine-driver-skytap v0.1.0

 I'm currently working on adding a VM to an existing environment that has a VPN attached. The VM is successfully added to my environment but does not start. When I run docker-machine with debug flag I get the following messages:

    (demo1) DBG | time="2016-05-19T16:38:41-07:00" level=info msg="Adding virtual machine" envId=... vmId=9646772 
    (demo1) DBG | time="2016-05-19T16:38:42-07:00" level=info msg="Merging a VM into environment" envId=... mergeBody=&{... [9646772]} 
    (demo1) DBG | time="2016-05-19T16:38:53-07:00" level=info msg="Attach network to VPN" envId=... netId=... vpnId=... 
    (demo1) DBG | time="2016-05-19T16:38:53-07:00" level=error msg="Unable to attach VPN to environment." envId=... error="The resource could not be found." networkId=... requestBody=&{...} vpnId=... 

I've double-checked the VPN ID and it looks correct. I'm not sure why it says it can't be found.

Any help is appreciated!
Thanks.

**Comment by dantjones** [comment]
VPNs have ACLs. If you login to Skytap (https://cloud.skytap.com) are you able to attach and connect the VPN?

**Comment by 5f6b3fb8** [comment]
OK, I was a bit confused. The environment already has the VPN attached, so I just need to omit the VPN ID option. I thought if the vpn was already attached, the script would recognize that and move on.

I think this issue can be closed.

The machine is up and running, but it looks like my dev box is trying to connect to the docker-machine using the internal 10.x.x.x instead of the nat'd 172.x.x.x. Are nat'd addresses supported?

**Comment by dantjones** [comment]
If adding the Docker host to an existing environment and you’re running Docker Machine on your local laptop, you still need to provide the VPN ID. The driver will check if the VPN is already attached or not and take appropriate action. It will then attempt to connect the VPN. The VPN has to be attached/connected in order for your laptop to connect. Both NAT and !NAT are supported should work. Note, if you’re attempting to configure a Swarm, Swarm does not yet support NAT’ing via Docker Machine. This is an issue with core Docker Machine functionality, not the Skytap driver.

**Comment by 5f6b3fb8** [comment]
We've resolved the issue, the documentation appears to be wrong for [Getting the VPN ID](http://help.skytap.com/kb-find-id-for-vm-environment-or-template.html#getvpnid).

The documentation states:

> The VPN ID is displayed in the browser address bar, after vpn-.
> For example, if the URL for environment is https://cloud.skytap.com/vpns/vpn-443322, the VPN ID number is 443322.

In order for the resource to be found, we needed the 'vpn-' as part of the ID.

This did not work for us:
docker-machine -D create --driver skytap ... --skytap-vpn-id 12345 ...

This works for us:
docker-machine -D create --driver skytap ... --skytap-vpn-id vpn-12345 ...
