### ISSUE TITLE
PreCreateCheck should fail if params are not valid.

### ISSUE THREAD

**Issue by kolds** [skytap/docker-machine-driver-skytap#17]
We should be doing PreCreateCheck validations. This will help prevent issues similiar to #16.

Some things we should validate:
Able to run requests using user_id and api_token.
vm_id exists.
env_id (if used) exists.
cpus, cpuspersocket, and ram are valid.

**Comment by dantjones** [comment]
Fixed by: [https://github.com/skytap/docker-machine-driver-skytap/commit/e0f09f6804d059c7eeefcb862224ccf5aa5fc532](https://github.com/skytap/docker-machine-driver-skytap/commit/e0f09f6804d059c7eeefcb862224ccf5aa5fc532)
