### ISSUE TITLE
skytap-ssh-user default should match user in template vm

### ISSUE THREAD

**Issue by kolds** [skytap/docker-machine-driver-skytap#18]
The template vms created to be used when creating docker hosts are setup to use `docker` for the ssh user. The default value for skytap_ssh_user should match this value.

**Comment by dantjones** [comment]
Fixed by: [https://github.com/skytap/docker-machine-driver-skytap/commit/8fe4c928380415688fc200a88debd493817445fd](https://github.com/skytap/docker-machine-driver-skytap/commit/8fe4c928380415688fc200a88debd493817445fd)
